---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cats/index":
    get:
      summary: list cats
      tags:
      - Cats
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 2797
                name: cat_name
                colour: 
                status: available
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
              - id: 2796
                name: cat_name
                colour: 
                status: available
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
              - id: 2795
                name: cat_name
                colour: 
                status: available
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
              - id: 2794
                name: cat_name
                colour: 
                status: available
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
              - id: 2793
                name: cat_name
                colour: 
                status: available
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
              - id: 2792
                name: cat_name
                colour: 
                status: unavailable
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
              - id: 2791
                name: cat_name
                colour: 
                status: unavailable
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
              - id: 2790
                name: cat_name
                colour: 
                status: unavailable
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
              - id: 2789
                name: cat_name
                colour: 
                status: unavailable
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
              - id: 2788
                name: cat_name
                colour: 
                status: unavailable
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
  "/api/v1/cats/show/{id}":
    get:
      summary: show cat
      tags:
      - Cats
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 2802
                name: cat_name
                colour: 
                status: unavailable
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
  "/api/v1/cats/available":
    get:
      summary: available cat
      tags:
      - Cats
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 2813
                name: cat_name
                colour: 
                status: available
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
              - id: 2814
                name: cat_name
                colour: 
                status: available
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
              - id: 2815
                name: cat_name
                colour: 
                status: available
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
              - id: 2816
                name: cat_name
                colour: 
                status: available
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
              - id: 2817
                name: cat_name
                colour: 
                status: available
                breed: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
  "/api/v1/litters/index":
    get:
      summary: list litters
      tags:
      - Litters
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 99
                name: litter_name
                mother:
                  id: 2818
                  name: cat_name
                  colour: 
                  status: unavailable
                  breed: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  mother_id: 
                  father_id: 
                  litter_id: 
                father:
                  id: 2819
                  name: cat_name
                  colour: 
                  status: unavailable
                  breed: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  mother_id: 
                  father_id: 
                  litter_id: 
                kittens: []
                date_of_creation: '2018-02-03'
                images: []
              - id: 100
                name: litter_name
                mother:
                  id: 2820
                  name: cat_name
                  colour: 
                  status: unavailable
                  breed: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  mother_id: 
                  father_id: 
                  litter_id: 
                father:
                  id: 2821
                  name: cat_name
                  colour: 
                  status: unavailable
                  breed: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  mother_id: 
                  father_id: 
                  litter_id: 
                kittens: []
                date_of_creation: '2018-02-03'
                images: []
              - id: 101
                name: litter_name
                mother:
                  id: 2822
                  name: cat_name
                  colour: 
                  status: unavailable
                  breed: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  mother_id: 
                  father_id: 
                  litter_id: 
                father:
                  id: 2823
                  name: cat_name
                  colour: 
                  status: unavailable
                  breed: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  mother_id: 
                  father_id: 
                  litter_id: 
                kittens: []
                date_of_creation: '2018-02-03'
                images: []
              - id: 102
                name: litter_name
                mother:
                  id: 2824
                  name: cat_name
                  colour: 
                  status: unavailable
                  breed: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  mother_id: 
                  father_id: 
                  litter_id: 
                father:
                  id: 2825
                  name: cat_name
                  colour: 
                  status: unavailable
                  breed: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  mother_id: 
                  father_id: 
                  litter_id: 
                kittens: []
                date_of_creation: '2018-02-03'
                images: []
              - id: 103
                name: litter_name
                mother:
                  id: 2826
                  name: cat_name
                  colour: 
                  status: unavailable
                  breed: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  mother_id: 
                  father_id: 
                  litter_id: 
                father:
                  id: 2827
                  name: cat_name
                  colour: 
                  status: unavailable
                  breed: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  mother_id: 
                  father_id: 
                  litter_id: 
                kittens: []
                date_of_creation: '2018-02-03'
                images: []
  "/api/v1/litters/show/{id}":
    get:
      summary: show litter
      tags:
      - Litters
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 108
                name: litter_name
                mother:
                  id: 2836
                  name: cat_name
                  colour: 
                  status: unavailable
                  breed: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  mother_id: 
                  father_id: 
                  litter_id: 
                father:
                  id: 2837
                  name: cat_name
                  colour: 
                  status: unavailable
                  breed: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  mother_id: 
                  father_id: 
                  litter_id: 
                kittens: []
                date_of_creation: '2018-02-03'
                images: []
servers:
- url: "/"
