---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/breeds/index":
    get:
      summary: list breeds
      tags:
      - Breeds
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 1116
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkVOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--32b5eeca9480a29c5e10e814b89d8bceebe06873/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 1115
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkFOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b0ae22e20d59e87122018250218eccc7bab82fdd/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 1114
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbThOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a53044f9fedb79799a12c1e30a06db458a0878c3/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 1113
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTROIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4b1d6872ee851f137ced4ca3c23ff8b31e271414/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 1112
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTBOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0793180c7829a27ba4b2f8248866ef422ede4ed4/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
  "/api/v1/breeds/show/{id}":
    get:
      summary: show breed
      tags:
      - Breeds
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1121
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbllOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f760c675132e856414a9ec27cf52a871f0b71b48/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
  "/api/v1/cats/available":
    get:
      summary: available cats
      tags:
      - Cats
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 830
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 1124
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                litter:
                  id: 234
                  name: litter_name
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjBOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2c67cdb7fdb63721c272d692411dcf772eeacd07/testst.png"
              - id: 831
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 1125
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                litter:
                  id: 234
                  name: litter_name
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjhOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4a2956481f1c7d054109408ca783df69e193c79a/testst.png"
              - id: 832
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 1126
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                litter:
                  id: 234
                  name: litter_name
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0VOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--977b316677341a1e3360922888f16496450cdcc3/testst.png"
              - id: 833
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 1127
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                litter:
                  id: 234
                  name: litter_name
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb01OIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e961c8ea37c567daf1c54500a753bc538a75aa81/testst.png"
              - id: 834
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 1128
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                litter:
                  id: 234
                  name: litter_name
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1VOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--989df42a1279975a7e5c233badd4e74d022c341d/testst.png"
  "/api/v1/cats/from_our_breeding":
    get:
      summary: from_our_breeding cats
      tags:
      - Cats
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 847
                name: cat_name
                colour: colour
                breed:
                  id: 1141
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUFOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0a63ad8427c8ea4e82064eead2d376e935135c1e/testst.png"
                mother: 
                father: 
              - id: 848
                name: cat_name
                colour: colour
                breed:
                  id: 1142
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUlOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a693683245cae6024b4a513a20f144cacd2f061f/testst.png"
                mother: 
                father: 
              - id: 849
                name: cat_name
                colour: colour
                breed:
                  id: 1143
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVFOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6e45b2467b0e85b2833bb1368269abc4a9e682b1/testst.png"
                mother: 
                father: 
              - id: 850
                name: cat_name
                colour: colour
                breed:
                  id: 1144
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVlOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1adde9884a7fd13f977adca5ce0fc153773a9b10/testst.png"
                mother: 
                father: 
              - id: 851
                name: cat_name
                colour: colour
                breed:
                  id: 1145
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWdOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--426278053102de5e35ba7139ef015b52574c6cc8/testst.png"
                mother: 
                father: 
  "/api/v1/litters/index":
    get:
      summary: list litters
      tags:
      - Litters
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 236
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTBOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4d82fc5e9541cf76ab5b14f7aa79df66d3b5fe8b/testst.png"
              - id: 237
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcklOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2284a8c5e3fba7de06dc07977dfe37bf279a51aa/testst.png"
              - id: 238
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmNOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9ae6da67db95f4801592907742518364581fade0/testst.png"
              - id: 239
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcndOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--27d3d56a5793d257bd94979c9f57e5e7ab6c638c/testst.png"
              - id: 240
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0VOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f905e275677a214c2f560d007007e17cabb12840/testst.png"
  "/api/v1/litters/show/{id}":
    get:
      summary: show litter
      tags:
      - Litters
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 245
                name: litter_name
                mother:
                  id: 870
                  name: cat_name
                  colour: colour
                  status: unavailable
                  breed:
                    id: 1164
                    name: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  personality: 
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGNOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d0c6a4c860e52ebae68bf51109e1baae842a3f6b/testst.png"
                father:
                  id: 871
                  name: cat_name
                  colour: colour
                  status: unavailable
                  breed:
                    id: 1165
                    name: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  personality: 
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGtOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a5ae1e93e22ecded8c749b8417791a33c9f09155/testst.png"
                kittens: []
                date_of_creation: '2018-02-03'
                images: []
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdG9OIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7325128c71a6b6db7862fb3a4691904fa5d2d7bc/testst.png"
  "/api/v1/news/index":
    get:
      summary: list news
      tags:
      - News
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 1266
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHNOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a951c9ccfe44b7eb04b6107a10e885553f4aeb22/testst.png"
                content: content
                video_url: video_url
              - id: 1267
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHdOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--535b0224668db62eba0be2cb2ae5c4555592b028/testst.png"
                content: content
                video_url: video_url
              - id: 1268
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDBOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0593dcfbcf58e71bd6e25e6972e73c49dcd5896b/testst.png"
                content: content
                video_url: video_url
              - id: 1269
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDROIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3a0e1784060e3806f20080e1a3746ea251dfc4f6/testst.png"
                content: content
                video_url: video_url
              - id: 1270
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDhOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8d3369650288938bcae373c8e135477d5fc6294c/testst.png"
                content: content
                video_url: video_url
              - id: 1271
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUFOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b8ec4dd863237db1cd16317f5b085b7dfe8b6fc4/testst.png"
                content: content
                video_url: video_url
  "/api/v1/news/relevant?news_limit={news_limit}":
    get:
      summary: relevant news
      tags:
      - News
      parameters:
      - name: news_limit
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 1272
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUVOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2bd6aaf6707b4d93ca4f78843471cd9eb65c67f5/testst.png"
                content: content
                video_url: video_url
              - id: 1273
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUlOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a94a486e1531667186577cc70b9674ea45e23a2c/testst.png"
                content: content
                video_url: video_url
              - id: 1274
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdU1OIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a4ab3992f686e7434faef358b7ea12e9d18c6db6/testst.png"
                content: content
                video_url: video_url
servers:
- url: "/"
