---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/breeds/index":
    get:
      summary: list breeds
      tags:
      - Breeds
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 805
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTRJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bc4a283a6447cfae7334359a545419b431091457/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 804
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTBJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f1c132bd296def55531e4dd5f7a6a6b89f9212ae/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 803
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXdJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bdf253875ff2a4058ae1a11ab245c8684a5e161f/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 802
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXNJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--145027acedfaed3279e0db078ae7b4a00f28b663/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 801
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdW9JIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--481efe1d8a7dcf677232b5ab993d6264a5f2a978/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
  "/api/v1/breeds/show/{id}":
    get:
      summary: show breed
      tags:
      - Breeds
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 810
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdk1JIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6833f0e2db9c485cd231ec5ff6ae28bb4ed444e2/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
  "/api/v1/cats/available":
    get:
      summary: available cat
      tags:
      - Cats
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 607
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 813
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                litter:
                  id: 171
                  name: litter_name
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdm9JIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--affe0fc31d6c3916209738b2a34e415de8e23398/testst.png"
              - id: 608
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 814
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                litter:
                  id: 171
                  name: litter_name
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdndJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cb9a0ba9f58e8c05b2a383c7e7df4a4a11cff54d/testst.png"
              - id: 609
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 815
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                litter:
                  id: 171
                  name: litter_name
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjRJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--863bfa082b3a144ca72ff1a9b5fd6d55945ac7e2/testst.png"
              - id: 610
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 816
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                litter:
                  id: 171
                  name: litter_name
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0FKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8b2681f6fb53192364e07a371c8940ddc7d95448/testst.png"
              - id: 611
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 817
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                litter:
                  id: 171
                  name: litter_name
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0lKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--15073e11085df090e9ed232a339a4bf45723ff9b/testst.png"
  "/api/v1/litters/index":
    get:
      summary: list litters
      tags:
      - Litters
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 172
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2NKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--14c7eebcecfa8769631b8e89eb1e37ace6c80ce8/testst.png"
              - id: 173
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3dKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c7b66c1ab9a9a5c771f1d64369b16c56711fb4c5/testst.png"
              - id: 174
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEVKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6d01809ec7c6f30557b46c215cecb61c4276e40f/testst.png"
              - id: 175
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFlKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4d45555fb05e40ff52b15f0c82c426887bc4f74f/testst.png"
              - id: 176
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHNKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c0e3178747cc1cfd2a1d0514f323ab9d5509c3c0/testst.png"
  "/api/v1/litters/show/{id}":
    get:
      summary: show litter
      tags:
      - Litters
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 181
                name: litter_name
                mother:
                  id: 630
                  name: cat_name
                  colour: colour
                  status: unavailable
                  breed:
                    id: 836
                    name: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  personality: 
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakVKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--253ecc6343dcbaebaf568cd8db1f8999ee66a9fc/testst.png"
                father:
                  id: 631
                  name: cat_name
                  colour: colour
                  status: unavailable
                  breed:
                    id: 837
                    name: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  personality: 
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBak1KIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--54954cbf9e5572a387e1542363aa44d6c553762c/testst.png"
                kittens: []
                date_of_creation: '2018-02-03'
                images: []
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalFKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3a4b97829e240c98e4847b57d9bab9e6719b265c/testst.png"
  "/api/v1/news/index":
    get:
      summary: list news
      tags:
      - News
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 708
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalVKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9069f9ff701cd5b33a070d4f39ca325d01fef6ff/testst.png"
                content: content
                video_url: video_url
              - id: 709
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBallKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--021e98379855bbc43910e16fae7b13eaea98153d/testst.png"
                content: content
                video_url: video_url
              - id: 710
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamNKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f130ff9f4aa91925e3fd5396c677ce6c9aec4008/testst.png"
                content: content
                video_url: video_url
              - id: 711
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamdKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e36e508c8948eb92500558d6814a7575edc30432/testst.png"
                content: content
                video_url: video_url
              - id: 712
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamtKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--902188a93964f6f45f38e698bcc450f9df18837a/testst.png"
                content: content
                video_url: video_url
              - id: 713
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBam9KIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5cf557270fb6e57d3d9c21579aee4035fec1b15a/testst.png"
                content: content
                video_url: video_url
  "/api/v1/news/relevant?news_limit={news_limit}":
    get:
      summary: relevant news
      tags:
      - News
      parameters:
      - name: news_limit
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 714
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanNKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1ffca45be9f33d346749b61d7a2004673fc7ade3/testst.png"
                content: content
                video_url: video_url
              - id: 715
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBandKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4f92e83b11fdb7fe3f96781718287030d433beb9/testst.png"
                content: content
                video_url: video_url
              - id: 716
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajBKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--41d9bc224659f4b09431c29529ea6d2d079cc683/testst.png"
                content: content
                video_url: video_url
servers:
- url: "/"
