---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/cats/index":
    get:
      summary: list cats
      responses:
        '200':
          description: successful
  "/api/v1/cats/show":
    get:
      summary: show cat
      responses:
        '200':
          description: successful
  "/api/v1/cats/available":
    get:
      summary: available cat
      responses:
        '200':
          description: successful
  "/api/v1/litters/index":
    get:
      summary: list litters
      responses:
        '200':
          description: successful
  "/api/v1/litters/show":
    get:
      summary: show litter
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
