---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/breeds/index":
    get:
      summary: list breeds
      tags:
      - Breeds
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 5
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--109bda279d07f8d3bb0d9f244cbf4fe17263bd1f/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 4
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26ade1a7f7a97284885d199746c2315d1610e1f5/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 3
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--83242fe12d3ad1ae10a672bb80dcea6938654138/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 2
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b1992a3c8bcd802e8935607e060f8210b8bf81a5/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 1
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ed42698a0ce261bdd65ef746511f0485dd98ea4/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
  "/api/v1/breeds/show/{id}":
    get:
      summary: show breed
      tags:
      - Breeds
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 10
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7a71fa0c0dc81a4b165b09c94fb685831fdce4cf/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
  "/api/v1/cats/available":
    get:
      summary: available cats
      tags:
      - Cats
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 3
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 13
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                litter:
                  id: 1
                  name: litter_name
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c316b156556223e9465102a9550d8158b5e5c52d/testst.png"
              - id: 4
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 14
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                litter:
                  id: 1
                  name: litter_name
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBHQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0fa465d73e8f894d2dc7cf43b3c038f8fb5bdf53/testst.png"
              - id: 5
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 15
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                litter:
                  id: 1
                  name: litter_name
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBHZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--156c6cd054793fe936ea58a0b72517e7026509bb/testst.png"
              - id: 6
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 16
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                litter:
                  id: 1
                  name: litter_name
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--07f42cbb7c149822b645c018b58f4eb929896eb0/testst.png"
              - id: 7
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 17
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                litter:
                  id: 1
                  name: litter_name
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8c74951ef06e3fd362817b984d729a84f44cf4ff/testst.png"
  "/api/v1/cats/from_our_breeding":
    get:
      summary: from_our_breeding cats
      tags:
      - Cats
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 20
                name: cat_name
                colour: colour
                breed:
                  id: 30
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBPUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--66e6eb9f7ba137e9fb951f5d54615df4cd320e8f/testst.png"
                mother:
                  id: 19
                  name: cat_name
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBOdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ab82742c65872f8c7b59f02f4c906e2a732c04e/testst.png"
                father:
                  id: 19
                  name: cat_name
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBOdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ab82742c65872f8c7b59f02f4c906e2a732c04e/testst.png"
              - id: 21
                name: cat_name
                colour: colour
                breed:
                  id: 31
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBPdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--375b251f37e9268c28e5b46f313eacb757ddcfe9/testst.png"
                mother:
                  id: 19
                  name: cat_name
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBOdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ab82742c65872f8c7b59f02f4c906e2a732c04e/testst.png"
                father:
                  id: 19
                  name: cat_name
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBOdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ab82742c65872f8c7b59f02f4c906e2a732c04e/testst.png"
              - id: 22
                name: cat_name
                colour: colour
                breed:
                  id: 32
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBQUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--53939cab4cdd0411d52948f7d41b6521c31b07c9/testst.png"
                mother:
                  id: 19
                  name: cat_name
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBOdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ab82742c65872f8c7b59f02f4c906e2a732c04e/testst.png"
                father:
                  id: 19
                  name: cat_name
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBOdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ab82742c65872f8c7b59f02f4c906e2a732c04e/testst.png"
              - id: 23
                name: cat_name
                colour: colour
                breed:
                  id: 33
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBQdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--92876c1b1d5266b5a732b89ed099113e2d9c171b/testst.png"
                mother:
                  id: 19
                  name: cat_name
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBOdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ab82742c65872f8c7b59f02f4c906e2a732c04e/testst.png"
                father:
                  id: 19
                  name: cat_name
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBOdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ab82742c65872f8c7b59f02f4c906e2a732c04e/testst.png"
              - id: 24
                name: cat_name
                colour: colour
                breed:
                  id: 34
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBRUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--06c398453fab491918c3e75c3d9d328bd662bd5e/testst.png"
                mother:
                  id: 19
                  name: cat_name
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBOdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ab82742c65872f8c7b59f02f4c906e2a732c04e/testst.png"
                father:
                  id: 19
                  name: cat_name
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBOdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ab82742c65872f8c7b59f02f4c906e2a732c04e/testst.png"
  "/api/v1/litters/index":
    get:
      summary: list litters
      tags:
      - Litters
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 3
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBSZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--91cd311fae1503820cfccb1418ed44f2b08e5a1a/testst.png"
              - id: 4
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--30b05e294af3bec6eddef699ed156a27aff2bd18/testst.png"
              - id: 5
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b5fa794b41c1229629d1fa835af90f5497d55be1/testst.png"
              - id: 6
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBWUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--df2d05938ebf30f9f36881a63b4c06a3e63ecd09/testst.png"
              - id: 7
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--30fd16d4716e028ebdfbf895e8fe19be88f07545/testst.png"
  "/api/v1/litters/show/{id}":
    get:
      summary: show litter
      tags:
      - Litters
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 12
                name: litter_name
                mother:
                  id: 43
                  name: cat_name
                  colour: colour
                  status: unavailable
                  breed:
                    id: 53
                    name: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  personality: 
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBjQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--298b22b53695c90a1e6e03fe1910a2e61453ef13/testst.png"
                father:
                  id: 44
                  name: cat_name
                  colour: colour
                  status: unavailable
                  breed:
                    id: 54
                    name: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  images: []
                  lineage_url: 
                  personality: 
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBjZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4e2490476f6f3602058cef8133f809e6e1cf9ed7/testst.png"
                kittens: []
                date_of_creation: '2018-02-03'
                images: []
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBjdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5abd0c1c96134b6976e1909c2c6c609dce91e2fb/testst.png"
  "/api/v1/news/index":
    get:
      summary: list news
      tags:
      - News
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 1
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBkQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--557103235b77c29bea8bccf7315ddb2f48a841a9/testst.png"
                content: content
                video_url: video_url
              - id: 2
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBkUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--73c60e72ba0536bda053e8c4621c2b00075240f0/testst.png"
                content: content
                video_url: video_url
              - id: 3
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBkZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bd5364fc50bbb7e442146efb085564516463340d/testst.png"
                content: content
                video_url: video_url
              - id: 4
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBkdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--40c93847519266ff761a930bf25e7b1bdab32743/testst.png"
                content: content
                video_url: video_url
              - id: 5
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBlQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4e4aac5442ca943874874ad98c473a32058acdbc/testst.png"
                content: content
                video_url: video_url
              - id: 6
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBlUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9e072198d223f281e7026ebbbb664a066896f7fd/testst.png"
                content: content
                video_url: video_url
  "/api/v1/news/relevant?news_limit={news_limit}":
    get:
      summary: relevant news
      tags:
      - News
      parameters:
      - name: news_limit
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 7
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBlZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--25a246cdba7366527b375111a6605b295fef4979/testst.png"
                content: content
                video_url: video_url
              - id: 8
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBldz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--03d47c1ee1d5ccc8eff8adabb6625b4af7051752/testst.png"
                content: content
                video_url: video_url
              - id: 9
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBmQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--54a0e36c3495893b2f20093bc091f0e8a4640a1f/testst.png"
                content: content
                video_url: video_url
servers:
- url: "/"
