---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/breeds/index":
    get:
      summary: list breeds
      tags:
      - Breeds
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 578
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVlGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ae8c386bbc0a743e8a69cf42adc94898d7966a02/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 577
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVVGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a9abf3e45fc821a0edaf333a313ffe3263f0682f/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 576
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVFGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--af4334a9dfc27dc18c6f43b4160459565dfa5078/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 575
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdU1GIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d8314c5503aec637a762868a6ff29ab02b30ab2f/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
              - id: 574
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUlGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0dfe9a5c36325ca8df86ab158b031e55aaec7104/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
  "/api/v1/breeds/show/{id}":
    get:
      summary: show breed
      tags:
      - Breeds
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 583
                name: breed_name
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXNGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f791f55641c204ff6e54229b63df2c689eb270cb/testst.png"
                history: history
                physical_attributes: physical_attributes
                allergy_informations: allergy_informations
  "/api/v1/cats/index":
    get:
      summary: list cats
      tags:
      - Cats
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 440
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 588
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
                health: 
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlVGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fffafc95f05364e7a9197b10c8274ddc6fe4172a/testst.png"
              - id: 439
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 587
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
                health: 
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdk1GIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bb9a90c073568db2993eeebb6970a2d9ca12905a/testst.png"
              - id: 438
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 586
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
                health: 
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkVGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8dc8bbbbb95bf207cb70da97470a785b034a344f/testst.png"
              - id: 437
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 585
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
                health: 
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdThGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0c79ac7fbb62cf571801e03f8b606efe4cbf5993/testst.png"
              - id: 436
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 584
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
                health: 
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTBGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ff1f5863e8c6d1f909a48846a090c5f58837b750/testst.png"
  "/api/v1/cats/show/{id}":
    get:
      summary: show cat
      tags:
      - Cats
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 445
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 593
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
                health: 
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjhGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c1b3684d28a28e4890011c109aa50a9d1e62ad56/testst.png"
  "/api/v1/cats/available":
    get:
      summary: available cat
      tags:
      - Cats
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 446
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 594
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
                health: 
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0VHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e0bf8d343b69a83c6bae53ad9a6d2f3486e164d2/testst.png"
              - id: 447
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 595
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
                health: 
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ01HIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--75f8e43ecce49fe624175ec2f2b809f22a32870a/testst.png"
              - id: 448
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 596
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
                health: 
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1VHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--36b4e7a8319fd0d44d11a5a56a6ee534e08b4b66/testst.png"
              - id: 449
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 597
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
                health: 
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2NHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1480857f6d2639d5b13b791e2b79e88151d2e9df/testst.png"
              - id: 450
                name: cat_name
                colour: colour
                status: available
                breed:
                  id: 598
                  name: breed_name
                breeding: breeding_name
                date_of_birth: '2018-02-03'
                sex: male
                images: []
                lineage_url: 
                mother_id: 
                father_id: 
                litter_id: 
                health: 
                personality: 
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2tHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--961d7315fde9f95f3e4f3058c1376c14300f45bd/testst.png"
  "/api/v1/litters/index":
    get:
      summary: list litters
      tags:
      - Litters
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 115
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzRHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6f378cbb4e400e32a70d4bad5343b44f765016f3/testst.png"
              - id: 116
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaE1HIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9156929d9d595390e12bd0fbac1899c256053a99/testst.png"
              - id: 117
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGdHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--99f9ddf395cd34da959e055ca1eba6541e13db25/testst.png"
              - id: 118
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDBHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f296db4e35f9186c634f3b8b51f98d414290e5c5/testst.png"
              - id: 119
                name: litter_name
                date_of_creation: '2018-02-03'
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUlHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c266317d56fd15af0be6d80da8bb1bc817e300fd/testst.png"
  "/api/v1/litters/show/{id}":
    get:
      summary: show litter
      tags:
      - Litters
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 124
                name: litter_name
                mother:
                  id: 469
                  name: cat_name
                  colour: colour
                  status: unavailable
                  breed:
                    id: 617
                    name: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamdHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2845aed6c08b713b18f8a615037317fdef67ab91/testst.png"
                father:
                  id: 470
                  name: cat_name
                  colour: colour
                  status: unavailable
                  breed:
                    id: 618
                    name: breed_name
                  breeding: breeding_name
                  date_of_birth: '2018-02-03'
                  sex: male
                  profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBam9HIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--684aebbb8a603245a58ce2ef94a697de16bfc3ca/testst.png"
                kittens: []
                date_of_creation: '2018-02-03'
                images: []
                profile_image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanNHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5c2ec44a74d54b2283f6b4c401cd64b0fe4bcd21/testst.png"
  "/api/v1/news/index":
    get:
      summary: list news
      tags:
      - News
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 384
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBandHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fbbf5d069768bff8d310562a56cd661920dde176/testst.png"
                content: content
                video_url: video_url
              - id: 385
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajBHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cace67176ccd27f9587be53b93d3e8f2408554c8/testst.png"
                content: content
                video_url: video_url
              - id: 386
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajRHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--50b71c36bbcce01e5ab8c09cd318e3321c903590/testst.png"
                content: content
                video_url: video_url
              - id: 387
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajhHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c9cb2729f30f4e2e805bfd948f6f2e17c74cda26/testst.png"
                content: content
                video_url: video_url
              - id: 388
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0FHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e661bd3b7673e9300b464020bf7dfd443a04be74/testst.png"
                content: content
                video_url: video_url
              - id: 389
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0VHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e6e069e430ea2441bb29786e0a7ad3b635a207e9/testst.png"
                content: content
                video_url: video_url
  "/api/v1/news/relevant?news_limit={news_limit}":
    get:
      summary: relevant news
      tags:
      - News
      parameters:
      - name: news_limit
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 390
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0lHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bee6863638db2c07a7ee532254ba9893d9040a36/testst.png"
                content: content
                video_url: video_url
              - id: 391
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa01HIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bb9e6188112b1613edb7fe4bf0aa6c09467f9db5/testst.png"
                content: content
                video_url: video_url
              - id: 392
                title: title
                image_url: "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1FHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5925e90044b155962aeff1390d6850f1448f4179/testst.png"
                content: content
                video_url: video_url
servers:
- url: "/"
